# BattleNight Version: ${project.version}
# Main Configuration File

UsePermissions: false
ReadyBlock: 42
InventoryType: save
FriendlyFire: false
StopHealthRegen: true
ExitWaypoint: false
Teleprtation:
    EnderPearls: true
    Portals: false
    Commands: true
    Plugins: false
Particles:
    ClassSelection: smoke
Commands:
    Block: true
    Whitelist:
    - list
    - me
    - toggledownfall
    - stop
    - reload
Debug: false
