name: BattleNight
author: LimeByte
version: ${project.version}
description: ${project.description}

main: org.battlenight.core.BattleNight
load: POSTWORLD

website: ${project.url}
dev-url: http://dev.bukkit.org/server-mods/battlenight/

commands:
    battlenight:
        description: Base BattleNight command
        aliases: [bn, battle]