# BattleNight Version: ${project.version}
# Main Configuration File

Battle:
    Type: TDM
    Duration: 5:00
UsePermissions: false
ReadyBlock: 42
FriendlyFire: false
StopHealthRegen: true
ExitWaypoint: false
Teleportation:
    EnderPearls: true
    Portals: false
    Commands: false
    Plugins: false
    Unknown: false
Particles:
    ClassSelection: smoke
Commands:
    Block: true
    Whitelist:
    - list
    - me
    - toggledownfall
    - stop
    - reload
UpdateCheck: true
Debug: false
