# BattleNight Version: ${project.version}
# Main Configuration File

Battle:
    Type: TDM
    Duration: 300
    MinPlayers: 2
    MaxPlayers: 0
UsePermissions: false
ReadyBlock: iron-block
FriendlyFire: false
StopHealthRegen: true
ExitWaypoint: false
Teleportation:
    EnderPearls: true
    Portals: true
    Commands: false
    Plugins: false
    Unknown: true
Particles:
    ClassSelection: smoke
Scoreboard:
    DisplayHealth: true
Commands:
    Block: true
    Whitelist:
    - list
    - me
    - toggledownfall
    - stop
    - reload
UpdateCheck: true
Debug: false
